bc{7}{7}{3}       
setpos{-12}{0}    
setheading{90}    
let{A}{30}        
let{C}{0}         
`repeat{7}        
|let{C}{C+1}      
|`repeat{5}       
||let{A}{A+5}     
||pc{C}{7-C}{3}   
||forward{A}      
||right{144}      
|~end             
~end              
pause{5}          
                  
                  
                  
                  
                  
